agrotech/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from .views import edit_profile
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.home,name='index'),
    path('message_sent/',views.MessageSent.as_view(),name='message_sent'),
    path('search_result/',views.SearchView.as_view(),name='search_result'),
    path('news/', include('blog.urls', namespace='blog')),
    path('gallery/',include('gallery.urls', namespace='gallery')),
    path('store/',include('store.urls',namespace='store')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('hitcount/', include(('hitcount.urls', 'hitcount'), namespace='hitcount')),
    path('accounts/', include('allauth.urls')),
    path('accounts/profile/', views.Profile.as_view(), name='profile'),
    path('accounts/profile/edit/', edit_profile, name='edit_profile'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/urls.py
from django.urls import path
from . import views
from django.contrib.admin.views.decorators import staff_member_required

app_name = 'blog'

urlpatterns = [
    path('',views.PostList.as_view(),name='post_list'),
    path('article/<slug:slug>',views.PostDetail.as_view(),name='post_detail'),
    path('new_article/',staff_member_required(views.PostCreate.as_view()),name='post_create'),
    path('article/<slug:slug>/edit',staff_member_required(views.PostUpdate.as_view()),name='post_update'),
    path('article/<slug:slug>/delete',staff_member_required(views.PostDelete.as_view()),name='post_delete'),
]

gallery/urls.py
from .views import *
from django.contrib.admin.views.decorators import staff_member_required
from django.urls import path

app_name = 'gallery'

urlpatterns = [
    path('', GalleryView.as_view(), name='index'),
    path('ajax/retrieve', RetrieveImages.as_view(), name='ajax_retrieve'),
    path('upload/', staff_member_required(UploadingImagesToTheGallery.as_view()), name='upload'),
]

gallery/models.py
# GALLERY MODELS
from django.db import models

# Create your models here.
class GalleryImage(models.Model):
    title = models.CharField(max_length = 100, blank = True, null = True)
    image = models.ImageField(upload_to='gallery')

gallery/forms.py
from django import forms

class MultipleImagesForm(forms.Form):
    image_field = forms.ImageField(widget=forms.ClearableFileInput(attrs={'multiple':True}))

gallery/views.py
from .forms import *
from .models import *
from django.core import serializers
from django.http import JsonResponse
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import FormView, ListView, View

# Displaying gallery images each time in the Index Page
displayingItemsNumber = 7 # IMPORTANT: Should be the same as in gallery.js

class GalleryView(ListView):
    model=GalleryImage
    context_object_name = 'gallery'
    template_name='gallery/gallery.html'

class RetrieveImages(View):
    def get(self, request):
        # Gets via ajax the requested indexes expressed in javascript
        fromIndex = int(request.GET.get('fromIndex', None))
        toIndex = int(request.GET.get('toIndex', None))

        # Checking pagination position
        first_page = False
        last_page = False
        if fromIndex > GalleryImage.objects.all().count()-1: # Is it going to the First Page?
            first_page = True
            fromIndex = 0
            toIndex = displayingItemsNumber
        elif fromIndex < 0: # Is it going to the Last Page?
            last_page = True
            fromIndex = (GalleryImage.objects.all().count() -
                GalleryImage.objects.all().count()%displayingItemsNumber)
            toIndex = GalleryImage.objects.all().count()

        if toIndex > GalleryImage.objects.all().count(): # Is it the Last Page and not full?
            toIndex = GalleryImage.objects.all().count()

        slicedListOfImages = serializers.serialize("json",GalleryImage.objects.all().order_by('id')[fromIndex:toIndex])
        data = {
            'slicedListOfImages': slicedListOfImages,
            'fromIndex': fromIndex,
            'toIndex': toIndex,
        }
        return JsonResponse(data)

class UploadingImagesToTheGallery(FormView):
    form_class = MultipleImagesForm
    template_name = 'gallery/upload.html'
    success_url = reverse_lazy('gallery:index')

    def post(self, request, *args, **kwargs):
        form_class = self.get_form_class()
        form = self.get_form(form_class)
        images = request.FILES.getlist('image_field')
        if form.is_valid():
            for i in images:
                image = GalleryImage.objects.create(image=i)
                image.save()
            return self.form_valid(form)
        else:
            return self.form_invalid(form)

gallery/templates/gallery/gallery.html
{% extends "base.html" %}
{% load static %}
{% block title %}Gallery{% endblock %}
{% block styles %}
  <link rel="stylesheet" type="text/css" href='{% static "css/gallery_list.css" %}'>
{% endblock %}
{% block content %}
<div class="heading d-flex justify-content-center">
  <div>
    <h1 class="text-center pb-5">Gallery</h1>
    {% if user.is_staff %}
      <a href="{% url 'gallery:upload' %}" class="btn btn-success w-100 mb-5">Upload Images</a>
    {% endif %}
  </div>
</div>
<div class="bg pb-5">
  <div class="gallery" id="gallery">
    {% for gallery_image in gallery %}
      <div class="gallery-item">
          <div class="content"><img onload="resizeAll()" src="{% get_media_prefix %}{{gallery_image.image}}" alt="{{gallery_image.title}}"></div>
      </div>
    {% endfor %}

  </div>
</div>

{% endblock %}
{% block scripts %}
  <script src='{% static "js/gallery_list.js" %}' charset="utf-8"></script>
{% endblock %}

gallery/templates/gallery/upload.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block content %}
<div class="min-vh-100 d-flex justify-content-center">
<div class="container">
<h1>Image Upload</h1>

<p>Upload one or more images here</p>

<form method="post" action="{% url 'gallery:upload' %}" id="form" enctype='multipart/form-data'>
  {% csrf_token %}
  {{ form|crispy }}
  <button class="btn btn-success" type="submit">Send</button>
</form>
</div>
</div>
{% endblock %}