agrotech/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from .views import edit_profile
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.home,name='index'),
    path('message_sent/',views.MessageSent.as_view(),name='message_sent'),
    path('search_result/',views.SearchView.as_view(),name='search_result'),
    path('news/', include('blog.urls', namespace='blog')),
    path('gallery/',include('gallery.urls', namespace='gallery')),
    path('store/',include('store.urls',namespace='store')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('hitcount/', include(('hitcount.urls', 'hitcount'), namespace='hitcount')),
    path('accounts/', include('allauth.urls')),
    path('accounts/profile/', views.Profile.as_view(), name='profile'),
    path('accounts/profile/edit/', edit_profile, name='edit_profile'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/urls.py
from django.urls import path
from . import views
from django.contrib.admin.views.decorators import staff_member_required

app_name = 'blog'

urlpatterns = [
    path('',views.PostList.as_view(),name='post_list'),
    path('article/<slug:slug>',views.PostDetail.as_view(),name='post_detail'),
    path('new_article/',staff_member_required(views.PostCreate.as_view()),name='post_create'),
    path('article/<slug:slug>/edit',staff_member_required(views.PostUpdate.as_view()),name='post_update'),
    path('article/<slug:slug>/delete',staff_member_required(views.PostDelete.as_view()),name='post_delete'),
]

blog/models.py
from django.db import models
from django.utils import timezone
from django.urls import reverse
from ckeditor_uploader.fields import RichTextUploadingField
from hitcount.models import HitCountMixin, HitCount
from django.contrib.contenttypes.fields import GenericRelation
from six import python_2_unicode_compatible
from slugify import slugify

# Create your models here.

# TODO: Create "Tag" class and link it by Foreign Key

@python_2_unicode_compatible
class Post(models.Model):
    title = models.CharField(max_length=100, unique=True)
    author = models.CharField(max_length=20)
    text = RichTextUploadingField(verbose_name="Content")
    image = models.ImageField(upload_to='blog/post_image', verbose_name="Main Picture", null=True, blank=True)
    publish_date = models.DateTimeField(auto_now_add=True)
    slug = models.SlugField(unique=True, max_length=100)
    hit_count_generic = GenericRelation(HitCount, object_id_field='object_pk',
     related_query_name='hit_count_generic_relation')

    def publish(self):
        self.publish_date = timezone.now()
        self.save()

    def get_absolute_url(self):
        return reverse("blog:post_detail", kwargs={'pk':self.pk})

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)
        return super(Post, self).save(*args, **kwargs)

    class Meta:
        ordering= ['-publish_date']

blog/forms.py
# Blog App Forms
from django import forms
from .models import Post
from ckeditor_uploader.widgets import CKEditorUploadingWidget

class PostForm(forms.ModelForm):
    title = forms.CharField(max_length=100)
    text = forms.CharField(widget=CKEditorUploadingWidget())
    author = forms.CharField(max_length=20)

    class Meta:
        model = Post
        fields = ('title', 'author', 'text','image')

    def __init__(self,*args,**kwargs):
        super().__init__(*args,**kwargs)
        self.fields['text'].label = "Content"
        self.fields['image'].label = "Main Picture"

blog/views.py
from django.http import HttpResponse
from django.shortcuts import render
from django.urls import reverse, reverse_lazy
from django.utils import timezone
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from hitcount.views import HitCountDetailView
from .models import Post
from .forms import PostForm
from hitcount.models import HitCount
from hitcount.views import HitCountMixin
from agrotech.views import get_ip

# Create your views here.

class PostList(ListView):
    model = Post
    paginate_by = 5
    allow_empty = False #Throws 404 if there is no Posts

    def listing(request):
        post_list = Post.objects.all()
        paginator = Paginator(post_list, 5)

    def get_context_data(self, **kwargs):
        context = super(PostList, self).get_context_data(**kwargs)
        print("--INFO: "+str(context['view'].request.user)+" entered News Page using the IP: "+ str(get_ip(context['view'].request)))
        most_viewed = Post.objects.order_by('-hit_count_generic__hits','-publish_date')
        has_previous_3pages = context["page_obj"].number > 3
        has_previous_2pages = context["page_obj"].number > 2
        has_next_2pages = context["paginator"].num_pages - context["page_obj"].number > 1
        has_next_3pages = context["paginator"].num_pages - context["page_obj"].number > 2
        context.update({
            'most_viewed':most_viewed,
            'has_previous_3pages':has_previous_3pages,
            'has_previous_2pages': has_previous_2pages,
            "has_next_2pages": has_next_2pages,
            "has_next_3pages":has_next_3pages})
        return context

    def get_queryset(self):
        for post in Post.objects.all():
            return Post.objects.filter(publish_date__lte = timezone.now()).order_by('-publish_date')

class PostDetail(HitCountDetailView):
    model = Post
    count_hit = True

    def get_context_data(self, **kwargs):
        context = super(PostDetail, self).get_context_data(**kwargs)
        context.update({
        'most_viewed': Post.objects.order_by('-hit_count_generic__hits')[:2],
        })
        return context

class PostCreate(CreateView):
    model = Post
    fields = ['title', 'author', 'image','text']

    def get_success_url(self):
        return reverse('blog:post_detail', kwargs={'slug' : self.object.slug})

    def get_form_kwargs(self, *args, **kwargs):
        kwargs = super(PostCreate, self).get_form_kwargs(
            *args, **kwargs)
        return kwargs

class PostUpdate(UpdateView):
    model = Post
    fields = ['title', 'author', 'image','text']

    def get_success_url(self):
        return reverse('blog:post_detail', kwargs={'slug' : self.object.slug})

    def get_form_kwargs(self, *args, **kwargs):
        kwargs = super(PostUpdate, self).get_form_kwargs(
            *args, **kwargs)
        return kwargs

class PostDelete(DeleteView):
    model = Post
    success_url = reverse_lazy('blog:post_list')

blog/templates/blog/post_confirm_delete.html
{% extends "base.html" %}
{% block title %}Are you sure you want to delete this article?{% endblock %}
{% block main_content %}
<div class="min-vh-100 d-flex justify-content-center">
<div class="container">
  <h1>Delete Article</h1>

  <p>Are you sure you want to delete the article "{{post}}"?</p>

  <form method="POST" action="{% url 'blog:post_delete' slug=post.slug %}">
    {% csrf_token %}
    <button class="btn btn-danger" type="submit">Delete</button>
  </form>
</div>
</div>
{% endblock %}

blog/templates/blog/post_detail.html
{% extends "base.html" %}
{% load static %}
{% load hitcount_tags %}
{% block title %}{{post.title}}{% endblock %}

{% block styles %}<link rel="stylesheet" type="text/css" href='{% static "css/post_detail.css" %}'>{% endblock %}

{% block main_content %}

<section>
  <div class="container post_header">
    <div class="d-flex justify-content-center section_title">
        <h2>News</h2>
    </div>
    <div class="post_info">
      <h1>{{post.title}}</h1>
      <div class="d-flex post_info_sub">
        <img src="{% static 'img/create_icon.svg' %}" alt="[pencil]">
        <p>By {{post.author}} </p>
      </div>
      <div class="d-flex post_info_sub">
        <img src="{% static 'img/clock.svg' %}" alt="[pencil]">
        <p>{{post.publish_date}}</p>
      </div>
      {% if user.is_staff %}
        <div class="d-flex post_info_sub">
          <a href="{% url 'blog:post_update' slug=post.slug %}">Edit</a>
        </div>
        <div class="d-flex post_info_sub">
          <a href="{% url 'blog:post_delete' slug=post.slug %}">Delete</a>
        </div>
      {% endif %}
    </div>
  </div>
</section>

<section class="container blog_post">
  {% if post.image %}
  <div class="img_container">
    <img src="{% get_media_prefix %}{{ post.image }}" alt="{{post.title}}">
  </div>
  {% endif %}
  {{post.text|safe}}
</section>

<section class="related_posts">
  <h1 class="section_title">Related Stories</h1>
  {% for article in most_viewed|slice:":2" %}
    {% if not article.pk == post.pk %}
      {% include "_post_preview-1.html" %}
    {% endif %}
  {% endfor %}
</section>

{% endblock %}

{% block scripts %}
  <script src="{% static 'js/news.js' %}" charset="utf-8"></script>
{% endblock %}

blog/templates/blog/post_form.html
{% extends "base.html" %}
{% load bootstrap3 %}
{% load crispy_forms_tags %}
{% block title %}New Article{% endblock %}
{% block main_content %}
<div class="min-vh-100 d-flex justify-content-center">
<div class="container mb-5">
  <h1>{% if post %}Edit{% else %}New{% endif %} Article</h1>

  <form method="POST" action="{% if post %}{% url 'blog:post_update' slug=post.slug %}{% else %}{% url 'blog:post_create' %}{% endif %}" enctype="multipart/form-data">
    {% csrf_token %}
    {{form.media}}
    {{ form|crispy }}
    <button class="btn btn-success" type="submit" name="action">Publish</button>
  </form>
</div>
</div>
{% endblock %}

blog/templates/blog/post_list.html
{% extends "base.html" %}
{% load static %}
{% load hitcount_tags %}
{% block title %}Agrevo News{% endblock %}
{% block styles %}<link rel="stylesheet" type="text/css" href='{% static "css/news.css" %}'>{% endblock %}
{% block main_content %}

<section id="launching">
  <div class="">
    <div class="launching_image" style="background: url({% static "img/830_11.jpg" %});"></div>
    <div class="circle_container">
      <svg viewBox="0 0 1078 1031" fill="none">
        <path d="M1004.5 515.5C1004.5 756.556 799.211 957.5 539 957.5C278.789 957.5 73.5 756.556 73.5 515.5C73.5 274.444 278.789 73.5 539 73.5C799.211 73.5 1004.5 274.444 1004.5 515.5Z" stroke="#1F6C34" stroke-width="147"/>
      </svg>
    </div>
    <div class="launching_text">
      <h1 id="welcome_label">Welcome</h1>
      <h1 id="to_agrevo_news_label">to AGREVO NEWS</h1>
    </div>
  </div>
</section>

<section class="most_recent">
  <div class="d-flex justify-content-center section_title">
      <h2>Most Recent</h2>
  </div>

  <div class="row">
  {% for article in post_list %}
    {% if forloop.counter == 1 and page_obj.number == 1 %}
      <div class="highlighted col-12">
        {% include "_post_preview-2.html" %}
      </div>
    {% else %}
      <div class="col-12 col-lg-6">
        {% include "_post_preview-2.html" %}
      </div>
    {% endif %}
    {% empty %}
      <p>No articles yet.</p>
  {% endfor %}
  </div>


{% if post_list %}
  <div class="d-flex justify-content-center">
    <div class="pagination">
      <a href="?page=1">
        <div class="first_page">
          <svg width="8" height="14" viewBox="0 0 8 14" fill="none" xmlns="http://www.w3.org/2000/svg">
            <path d="M7.21875 13.8125L7.84375 13.2188C7.96875 13.0625 7.96875 12.8125 7.84375 12.6875L2.1875 7L7.84375 1.34375C7.96875 1.21875 7.96875 0.96875 7.84375 0.8125L7.21875 0.21875C7.0625 0.0625 6.84375 0.0625 6.6875 0.21875L0.125 6.75C0 6.90625 0 7.125 0.125 7.28125L6.6875 13.8125C6.84375 13.9688 7.0625 13.9688 7.21875 13.8125Z" fill="#BDBDBD" fill-opacity="0.98"/>
          </svg>
        </div>
      </a>
      {% if page_obj.number == paginator.num_pages and has_previous_3pages %}
      <a href="?page={{ page_obj.number|add:"-3" }}">
        <div class="page_square">
          {{ page_obj.number|add:"-3" }}
        </div>
      </a>
      {% endif %}
      {% if has_previous_2pages %}
      <a href="?page={{ page_obj.number|add:"-2" }}">
        <div class="page_square">
          {{ page_obj.number|add:"-2" }}
        </div>
      </a>
      {% endif %}
      {% if page_obj.has_previous %}
      <a href="?page={{ page_obj.previous_page_number }}">
        <div class="page_square">
          {{ page_obj.number|add:"-1" }}
        </div>
      </a>
      {% endif %}
      <div class="page_square">
        {{ page_obj.number }}
      </div>
      {% if page_obj.has_next %}
      <a href="?page={{ page_obj.next_page_number }}">
        <div class="page_square">
          {{ page_obj.number|add:"1" }}
        </div>
      </a>
      {% endif %}
      {% if has_next_2pages %}
      <a href="?page={{ page_obj.number|add:"2" }}">
        <div class="page_square">
          {{ page_obj.number|add:"2" }}
        </div>
      </a>
      {% endif %}
      {% if page_obj.number == 1 and has_next_3pages %}
      <a href="?page={{ page_obj.number|add:"3" }}">
        <div class="page_square">
          {{ page_obj.number|add:"3" }}
        </div>
      </a>
      {% endif %}
      <a href="?page={{ page_obj.paginator.num_pages }}">
        <div class="last_page">
          <svg width="8" height="14" viewBox="0 0 8 14" fill="none" xmlns="http://www.w3.org/2000/svg">
            <path d="M0.75 0.21875L0.125 0.8125C0 0.96875 0 1.21875 0.125 1.34375L5.78125 7L0.125 12.6875C0 12.8125 0 13.0625 0.125 13.2188L0.75 13.8125C0.90625 13.9688 1.125 13.9688 1.28125 13.8125L7.84375 7.28125C7.96875 7.125 7.96875 6.90625 7.84375 6.75L1.28125 0.21875C1.125 0.0625 0.90625 0.0625 0.75 0.21875Z" fill="#BDBDBD" fill-opacity="0.98"/>
          </svg>
        </div>
      </a>
    </div>
  </div>
{% endif %}

</section>

<section class="most_viewed">
  <div class="d-flex justify-content-center section_title">
      <h2>Most Viewed</h2>
  </div>
    {% for article in most_viewed|slice:":5" %}
      <div class="position-relative">
        <div class="rank">0{{forloop.counter}}</div>
        {% include "_post_preview-1.html" %}
      </div>
    {% endfor %}
</section>
{% endblock %}

{% block scripts %}
  <script src="{% static 'js/news.js' %}" charset="utf-8"></script>
{% endblock %}