agrotech/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from .views import edit_profile
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.home,name='index'),
    path('message_sent/',views.MessageSent.as_view(),name='message_sent'),
    path('search_result/',views.SearchView.as_view(),name='search_result'),
    path('news/', include('blog.urls', namespace='blog')),
    path('gallery/',include('gallery.urls', namespace='gallery')),
    path('store/',include('store.urls',namespace='store')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('hitcount/', include(('hitcount.urls', 'hitcount'), namespace='hitcount')),
    path('accounts/', include('allauth.urls')),
    path('accounts/profile/', views.Profile.as_view(), name='profile'),
    path('accounts/profile/edit/', edit_profile, name='edit_profile'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/urls.py
from django.urls import path
from . import views
from django.contrib.admin.views.decorators import staff_member_required

app_name = 'blog'

urlpatterns = [
    path('',views.PostList.as_view(),name='post_list'),
    path('article/<slug:slug>',views.PostDetail.as_view(),name='post_detail'),
    path('new_article/',staff_member_required(views.PostCreate.as_view()),name='post_create'),
    path('article/<slug:slug>/edit',staff_member_required(views.PostUpdate.as_view()),name='post_update'),
    path('article/<slug:slug>/delete',staff_member_required(views.PostDelete.as_view()),name='post_delete'),
]

templates/_post_preview-1.html
{% load static %}
<div class="related_story_card d-flex">
  <div class="post_info m-auto">
    <div class="mx-auto">
      <div class="outer d-flex align-items-end">
        <h1>{{ article.title }}</h1>
      </div>
      <div class="d-flex post_info_sub">
        <img src="{% static 'img/create_icon.svg' %}" alt="[pencil]">
        <p>By {{ article.author }}</p>
      </div>
      <div class="d-flex post_info_sub">
        <img src="{% static 'img/clock.svg' %}" alt="[pencil]">
        <p>{{ article.publish_date }}</p>
      </div>
      <a href="{% url 'blog:post_detail' slug=article.slug %}" class="btn">read</a>
    </div>
  </div>
  <div class="card_background_image" style="background: url({% get_media_prefix %}{{ article.image }}) no-repeat;">
  </div>
</div>

templates/_post_preview-2.html
{% load static %}
<div class="article_card d-flex flex-column">
  <div class="card_background_image" style="background: url({% get_media_prefix %}{{ article.image }}) no-repeat;"></div>
  <div class="post_info">
    <div class="outer d-flex align-items-end">
      <h1>{{ article.title }}</h1>
    </div>
    <div class="d-flex post_info_sub">
      <img src="{% static 'img/create_icon.svg' %}" alt="[pencil]">
      <p>By {{ article.author }}</p>
    </div>
    <div class="d-flex post_info_sub">
      <img src="{% static 'img/clock.svg' %}" alt="[pencil]">
      <p>{{ article.publish_date }}</p>
    </div>
    <a href="{% url 'blog:post_detail' slug=article.slug %}" class="btn">read</a>
  </div>
</div>

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %} - AGREVO LIFE</title>

    {# FAVICON #}
    <link rel="icon" type="image/png" href="{% static 'img/logo_agrotech_food.png' %}" />

    {# Bootstrap #}
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    {# custom CSS #}
    <link rel="stylesheet" type="text/css" href="{% static 'css/master.css' %}">
    {% block styles %}{% endblock %}

</head>

<body>

    <header>
        <nav class="navbar navbar-expand-xl navbar-light bg_agro-light">
            <a class="navbar-brand" href="{% url 'index' %}">
                <img src="{% static 'img/logo_agrotech_food.png' %}" alt="Agrotech Food Logo">
            </a>
            <div class="d-none d-lg-block d-xl-none ml-auto">
                <ul class="nav ml-auto">
                    <li class="nav-item">
                        <a class="nav-link" href="{% if not url_name == 'index' %}{% url 'index' %}{% endif %}#about_us">about us</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% if url_name == 'index' %}#news{% else %}{% url 'blog:post_list' %}{% endif %}">news</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% if not url_name == 'index' %}{% url 'index' %}{% endif %}#contact">contact</a>
                    </li>
                </ul>
            </div>

            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item">
                        <a class="nav-link d-lg-none d-xl-block" href="{% if not url_name == 'index' %}{% url 'index' %}{% endif %}#about_us">about us</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% if not url_name == 'index' %}{% url 'index' %}{% endif %}#vision">vision</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link d-lg-none d-xl-block" href="{% if url_name == 'index' %}#news{% else %}{% url 'blog:post_list' %}{% endif %}">news</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% if not url_name == 'index' %}{% url 'index' %}{% endif %}#technology">technology</a>
                    </li>
                    <li class="nav-item d-none">
                        <a class="nav-link" href="{% url 'store:index' %}">store</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link d-lg-none d-xl-block" href="{% if not url_name == 'index' %}{% url 'index' %}{% endif %}#contact">contact</a>
                    </li>
                    {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link d-lg-none d-xl-block" href="{% url 'profile' %}">Staff</a>
                    </li>
                    {% endif %}
                </ul>
                <form method="GET" action="{% url 'search_result' %}" class="form-inline my-2 my-lg-0 position-relative">
                    <input class="form-control mr-sm-2" name="search_input" type="search" aria-label="Search">
                    <button class="btn position-absolute" type="submit">
                        <img src='{% static "img/search_icon.svg" %}' alt="Search Button">
                    </button>
                </form>
            </div>
        </nav>
    </header>

    <main>
      {% block main_content %}{% endblock %}
      {% block content %}{% endblock %}{# 3rd-party apps use "content" #}
    </main>

    <footer>
        <nav class="navbar navbar-expand navbar-light justify-content-center">
            <ul class="navbar-nav justify-content-between">
              <li class="nav-item">
                <a class="nav-link" href="{% if not url_name == 'index' %}{% url 'index' %}{% endif %}#about_us">about us</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% if not url_name == 'index' %}{% url 'index' %}{% endif %}#vision">vision</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% if url_name == 'index' %}#news{% else %}{% url 'blog:post_list' %}{% endif %}">news</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% if not url_name == 'index' %}{% url 'index' %}{% endif %}#technology">technology</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% if not url_name == 'index' %}{% url 'index' %}{% endif %}#contact">contact</a>
              </li>
            </ul>
        </nav>
        <div class="d-flex justify-content-center">
            <a href="https://www.facebook.com/Agrevo-Life-108834874134521/?modal=admin_todo_tour">
                <div class="svg-container">
                  <svg viewBox="0 0 22 22" preserveAspectRatio="xMinYMin meet" class="svg-content">
                    <path fill-rule="evenodd" clip-rule="evenodd" d="M3.66671 1.8335H18.3334C19.3459 1.8335 20.1667 2.65431 20.1667 3.66683V18.3335C20.1667 19.346 19.3459 20.1668 18.3334 20.1668H3.66671C2.65419 20.1668 1.83337 19.346 1.83337 18.3335V3.66683C1.83337 2.65431 2.65419 1.8335 3.66671 1.8335ZM3.66671 3.6669V18.3336H18.3334V3.6669H3.66671ZM10.2053 11.0041H11.9167V16.5001H13.75V11.0041H15.5673V9.17079H13.75V8.25009C13.75 7.74383 14.1604 7.33343 14.6667 7.33343H15.5834V5.50009H14.6667C13.1479 5.50009 11.9167 6.73131 11.9167 8.25009V9.17079H10.2053V11.0041Z"/>
                  </svg>
                </div>
            </a>
        </div>
    </footer>

    <!-- Scripts -->
    {# jQuery #}
    <script src="https://code.jquery.com/jquery-3.5.1.min.js" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>

    {# Bootstrap #}
    {# <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script> #}
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

    {% block scripts %}{% endblock %}

    <!-- !END Scripts -->
</body>

</html>

templates/message_sent.html
{% extends "base.html" %}
{% load static %}
{% block title %}Message Sent{% endblock %}
{% block styles %}<link rel="stylesheet" href="{% static '/css/message_sent.css' %}">  {% endblock %}
{% block main_content %}
  <section class="message_sent">
      <h2>Message Sent.</h2>
      <h1>Thank you.</h1>
      <div class="d-flex justify-content-center">
        <a href="{% url 'index' %}">
          <div class="return_container" style="background: url({% static 'img/Ellipse_2.svg' %}) no-repeat">
            Return to the "Top Page"
          </div>
        </a>
      </div>
  </section>
{% endblock %}

templates/search_result.html
{% extends "base.html" %}
{% load static %}
{% load hitcount_tags %}
{% block title %}Results for "{{input}}"{% endblock %}
{% block styles %}<link rel="stylesheet" type="text/css" href='{% static "css/search_result.css" %}'>{% endblock %}
{% block content %}

<section class="related_posts">
{% if result|length > 0 %}
  <h1 class="section_title mb-5">{{result|length}} Result{{ result|pluralize }} for "{{input}}":</h1>
{% else %}
  <h1 class="section_title mb-5">No Results for "{{input}}".</h1>
{% endif %}
  {% for article in result %}
    {% if not article.pk == post.pk %}
      {% include "_post_preview-1.html" %}
    {% endif %}
  {% endfor %}

  {% if showGoToLogin %}
  <div>
    <p>Are you looking for the login page?</p>
    <a href="{% url 'account_login' %}" class="btn btn-success">Sign In</a>
  </div>
  {% endif %}
</section>

{% endblock %}